volumes:
    # sqldata:
    #     driver: local
    pgdata:
        driver: local
    dflat-vendor:
        driver: local
    dflat-appstorage:
        driver: local
    dflat-node-modules:
        driver: local

services:
    # MYSQL
    db:
        container_name: "dflat-db"
        build:
            context: "./_services/postgres"
            dockerfile: "./no-amqp.Dockerfile"
            args:
                - POSTGRES_USER=${POSTGRES_USER}
            target: development
        volumes:
            - "pgdata:${PGDATA}"
        env_file: .env
        expose:
            - 5432
            - 443
        # ports:
        #     - 85432:5432

    backend:
        container_name: "dflat-backend"
        build:
            context: "."
            dockerfile: "./_services/app/laravel_api.Dockerfile"
            target: development
            args:
                - _DOMAIN=dflat
        expose:
            - 443
        ports:
            - "8080:80"

        env_file: .env

        volumes:
            - dflat-vendor:/var/www/html/vendor
            - dflat-appstorage:/var/www/html/storage
            - ./app_backend/:/var/www/html/
        depends_on:
            db:
                condition: service_healthy

    frontend:
        container_name: dflat-frontend
        build:
            context: "."
            dockerfile: "_services/frontend/vue.Dockerfile"
        volumes:
            - dflat-node-modules:/app/node_modules
        ports:
            - "80:5173"
