volumes:
    # sqldata:
    #     driver: local
    pgdata:
        driver: local
    dflat-vendor:
        driver: local
    dflat-appstorage:
        driver: local
    dflat-node_modules:
        driver: local

services:
    # MYSQL
    db:
        container_name: "dflat-db"
        build:
            context: "./_services/postgres"
            dockerfile: "./no-amqp.Dockerfile"
            args:
                - POSTGRES_USER=postgres
            target: development
        volumes:
            - "pgdata:/var/lib/postgresql/"
        env_file:
            - .env
        expose:
            - 5432
        # ports:
        #     - "${DB_PORT_OUTER}:${DB_PORT_INNER}"

    app_backend:
        container_name: "dflat-backend"
        build:
            context: "."
            dockerfile: "./_services/app/laravel_api.Dockerfile"
            target: development
            args:
                - _DOMAIN=dflat
        expose:
            - 443
        ports:
            - "8080:80"

        volumes:
            - dflat-vendor:/var/www/html/vendor
            - dflat-appstorage:/var/www/html/storage
        depends_on:
            db:
                condition: service_healthy

    app_frontend:
        container_name: dflat-frontend
        build:
            context: "."
            dockerfile: "_services/frontend/vue.Dockerfile"
        volumes:
            - dflat-node_modules:/app/node_modules
        # depends_on:
        #     app_backend:
        #         condition: service_healthy
        ports:
            - "80:5173"
