# x-app_backend-common: &app_backend-common container_name:"${}"

volumes:
    # sqldata:
    #     driver: local
    pgdata:
        driver: local

services:
    # MYSQL
    db:
        container_name: "test_db"
        build:
            context: "./_services/postgres"
            dockerfile: "./no-amqp.Dockerfile"
            args:
                - POSTGRES_USER=postgres
            target: development
        volumes:
            - "pgdata:/var/lib/postgresql/"
        environment:
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DATABASE=dflat
        expose:
            - 5432
        # ports:
        #     - "${DB_PORT_OUTER}:${DB_PORT_INNER}"

    app_backend:
        # <<: *app_backend-common
        container_name: "test_backend"
        build:
            context: "."
            dockerfile: "./_services/app/laravel_api.Dockerfile"
            target: development
            args:
                - _DOMAIN=dflat
        expose:
            - 443
        ports:
            - "8080:80"
        depends_on:
            db:
                condition: service_healthy

    # app_frontend:
    #     build:
    #         context: "./_services/"
    #         dockerfile: "./${FRONTEND_SERVICE_NAME}/Dockerfile.dev"
    #         args:
    #             - "USERNAME=${SERVICES_USERNAME}"
    #             - "USERGROUP=${SERVICES_USERGROUP}"
    #     container_name: "${FRONTEND_SERVICE_NAME}"
    #     depends_on:
    #         app_backend:
    #             condition: service_healthy
    #     ports:
    #         - "80:${FRONTEND_PORT}"
